kind: pipeline
name: default

steps:
- name: Build
  image: golang
  commands:
  - go build
  - go test
  - sleep 120

- name: Test
  image: alpine
  commands:
  - pwd
  - ls -alh
  - ls -alh /
  - echo 'Hello from Drone... Dumping environment:'
  - env
  - echo "moving on...."


- name: Pack
  image: ubuntu
  commands: 
  - ls -alh 
  - ls -alh /
  - sleep 120
  - echo "All done"

