version: 2.1

jobs:
  build:

    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/benr/gohi
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run: go build 
      - store_artifacts:
          path: /go/src/github.com/benr/gohi/gohi
          destination: gohi

  runme:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/benr/gohi
    steps:
      - run: ./gohi

workflows:
  version: 2
  build_n_test:
    jobs:
      - build
      - runme:
          requires:
            - build